const palette = {
  primary: "#0061FF",
  primaryLight: "#D6E4FF",
  primaryDark: "#003D99",
  secondary: "#8C8E98",
  white: "#FFFFFF",
  black: "#000000",
  background: "#FFFFFF",
  gray100: "#F5F5F5",
  gray200: "#E8E8E8",
  gray300: "#C5C5C5",
  gray500: "#8C8E98",
  gray700: "#44444C",
  gray900: "#1A1A2E",
  darkBackground: "#0C0C0C",
  darkSecondary: "#1C1C1E",
  darkBorder: "#38383A",
  danger: "#FF5F5F",
  success: "#28A745",
};

export const Colors = {
  light: {
    text: palette.gray900,
    background: palette.background,
    tint: palette.primary,
    icon: palette.gray500,
    tabIconDefault: palette.gray500,
    tabIconSelected: palette.primary,
    border: palette.gray200,
    card: palette.white,
    placeholder: palette.gray500,
  },
  dark: {
    text: palette.white,
    background: palette.darkBackground,
    tint: palette.primary,
    icon: palette.gray300,
    tabIconDefault: palette.gray300,
    tabIconSelected: palette.primaryLight,
    border: palette.darkBorder,
    card: palette.darkSecondary,
    placeholder: palette.gray500,
  },
};